version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aplazo-backend-challenge-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aplazo-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: adminadmin
    depends_on:
      - postgres

  postgres:
    image: postgres:16.8
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aplazo-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminadmin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
